### ISSUE TITLE
Seeding error

### ISSUE THREAD

**Issue by leesheppard** [pacificalabs/propertyser#1]
@tarun-pacifica Seeding fails

<img width="929" alt="Screenshot 2024-08-19 at 9 41 07 PM" src="https://github.com/user-attachments/assets/7cff51ca-2661-4180-9917-e5bb726fd876">

**Comment by leesheppard** [comment]
rails db:seed --trace
** Invoke db:seed (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke db:load_config
** Execute db:abort_if_pending_migrations
0 apartments present.
0 users present.
destroy_models
Time to destroy models
  0.020652   0.001442   0.022094 (  0.031730)
bin/rails aborted!
ActiveModel::UnknownAttributeError: unknown attribute 'name' for Apartment. (ActiveModel::UnknownAttributeError)

          raise UnknownAttributeError.new(self, k.to_s)
          ^^^^^
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activemodel-7.2.0/lib/active_model/attribute_assignment.rb:53:in `rescue in _assign_attribute'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activemodel-7.2.0/lib/active_model/attribute_assignment.rb:46:in `_assign_attribute'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.0/lib/active_record/attribute_assignment.rb:15:in `block in _assign_attributes'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.0/lib/active_record/attribute_assignment.rb:9:in `each'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.0/lib/active_record/attribute_assignment.rb:9:in `_assign_attributes'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activemodel-7.2.0/lib/active_model/attribute_assignment.rb:34:in `assign_attributes'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activemodel-7.2.0/lib/active_model/api.rb:81:in `initialize'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.0/lib/active_record/core.rb:458:in `initialize'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.0/lib/active_record/inheritance.rb:76:in `new'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.0/lib/active_record/inheritance.rb:76:in `new'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.0/lib/active_record/persistence.rb:37:in `create'
/Users/leesheppard/Development/propertyser/db/seeds.rb:87:in `<main>'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/engine.rb:562:in `load'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/engine.rb:562:in `block in load_seed'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.0/lib/active_support/execution_wrapper.rb:91:in `wrap'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/engine.rb:648:in `block (2 levels) in <class:Engine>'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:130:in `instance_exec'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:141:in `run_callbacks'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/engine.rb:562:in `load_seed'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.0/lib/active_record/tasks/database_tasks.rb:489:in `load_seed'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.0/lib/active_record/railties/databases.rake:405:in `block (2 levels) in <main>'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/application.rb:188:in `invoke_task'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/application.rb:138:in `each'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/application.rb:138:in `block in top_level'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/application.rb:147:in `run_with_threads'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/application.rb:132:in `top_level'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/commands/rake/rake_command.rb:27:in `block (2 levels) in perform'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/commands/rake/rake_command.rb:27:in `block in perform'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/commands/rake/rake_command.rb:44:in `block in with_rake'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/rake_module.rb:59:in `with_application'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/command.rb:156:in `invoke_rake'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/command.rb:73:in `block in invoke'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/command.rb:149:in `with_argv'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/command.rb:69:in `invoke'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/commands.rb:18:in `<main>'
/Users/leesheppard/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
/Users/leesheppard/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'

Caused by:
NoMethodError: undefined method `name=' for an instance of Apartment (NoMethodError)
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activemodel-7.2.0/lib/active_model/attribute_methods.rb:507:in `method_missing'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.0/lib/active_record/attribute_methods.rb:491:in `method_missing'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activemodel-7.2.0/lib/active_model/attribute_assignment.rb:48:in `public_send'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activemodel-7.2.0/lib/active_model/attribute_assignment.rb:48:in `_assign_attribute'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.0/lib/active_record/attribute_assignment.rb:15:in `block in _assign_attributes'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.0/lib/active_record/attribute_assignment.rb:9:in `each'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.0/lib/active_record/attribute_assignment.rb:9:in `_assign_attributes'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activemodel-7.2.0/lib/active_model/attribute_assignment.rb:34:in `assign_attributes'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activemodel-7.2.0/lib/active_model/api.rb:81:in `initialize'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.0/lib/active_record/core.rb:458:in `initialize'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.0/lib/active_record/inheritance.rb:76:in `new'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.0/lib/active_record/inheritance.rb:76:in `new'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.0/lib/active_record/persistence.rb:37:in `create'
/Users/leesheppard/Development/propertyser/db/seeds.rb:87:in `<main>'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/engine.rb:562:in `load'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/engine.rb:562:in `block in load_seed'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.0/lib/active_support/execution_wrapper.rb:91:in `wrap'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/engine.rb:648:in `block (2 levels) in <class:Engine>'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:130:in `instance_exec'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:141:in `run_callbacks'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/engine.rb:562:in `load_seed'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.0/lib/active_record/tasks/database_tasks.rb:489:in `load_seed'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/activerecord-7.2.0/lib/active_record/railties/databases.rake:405:in `block (2 levels) in <main>'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/application.rb:188:in `invoke_task'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/application.rb:138:in `each'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/application.rb:138:in `block in top_level'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/application.rb:147:in `run_with_threads'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/application.rb:132:in `top_level'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/commands/rake/rake_command.rb:27:in `block (2 levels) in perform'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/commands/rake/rake_command.rb:27:in `block in perform'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/commands/rake/rake_command.rb:44:in `block in with_rake'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/rake-13.2.1/lib/rake/rake_module.rb:59:in `with_application'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/command.rb:156:in `invoke_rake'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/command.rb:73:in `block in invoke'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/command.rb:149:in `with_argv'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/command.rb:69:in `invoke'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/railties-7.2.0/lib/rails/commands.rb:18:in `<main>'
/Users/leesheppard/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
/Users/leesheppard/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
/Users/leesheppard/.rvm/gems/ruby-3.3.4/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:seed
